[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/google-reviews"
  to = "/.netlify/functions/google-reviews"
  status = 200

[[redirects]]
  from = "/api/submit-lead"
  to = "/.netlify/functions/submit-lead"
  status = 200
